[package]
name = "meme_quicksilver"
version = "0.1.0"
authors = ["Paul Houghton <paulirotta@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# quicksilver="0.3"

#[target.'cfg(target_arch = "x86_64")'.dependencies]
#quicksilver = {git = "https://github.com/paulirotta/quicksilver.git", branch="image-fix-test"}

#[target.'cfg(not(target_arch = "x86_64"))'.dependencies]
quicksilver = {git = "https://github.com/paulirotta/quicksilver.git", branch="v3-gl3-i8u8-fix"}

[profile.release]
opt-level = 'z'
lto = true

